version: '3.6'

services:

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf/:/etc/mysql/conf.d
    networks:
      - sonarnet
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  prometheus:
    image: prom/prometheus:v2.2.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana:5.1.4
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/etc/grafana/
      - grafana_data:/grafana
    env_file:
      - grafana/config.monitoring
    restart: always

  sonarqube:
    image: sonarqube:7.1
    container_name: sonarqube
    depends_on:
      - mysql
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonarnet
    command: -Dsonar.web.context=/sonar
    ports:
      - 9000:9000
      - 9092:9092
    environment:
      - SONAR_JDBC_URL=jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8
    restart: always

networks:
  sonarnet:
    driver: bridge
volumes:
  prometheus_data:
  grafana_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins: