CREATE SCHEMA IF NOT EXISTS "public";

DROP TABLE PUBLIC.GOODS_TBL;

CREATE TABLE IF NOT EXISTS GOODS_TBL(
  ID BIGINT(10) DEFAULT 0 NOT NULL AUTO_INCREMENT ,
  VERSION INT(5) UNSIGNED NOT NULL DEFAULT '0' ,
  CODE VARCHAR(10) UNIQUE NOT NULL ,
  NAME VARCHAR(25) NOT NULL ,
  PRICE SMALLINT(4) UNSIGNED ,
  NOTE VARCHAR(64) NOT NULL ,
  CREATE_DATETIME DATETIME NOT NULL ,
  UPDATE_DATETIME DATETIME NOT NULL
);

INSERT INTO GOODS_TBL (VERSION ,CODE ,NAME ,PRICE ,NOTE ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (1,'CODE1','FIND',1,'NOTE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO GOODS_TBL (VERSION ,CODE ,NAME ,PRICE ,NOTE ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (1,'CODE2','GET',1,'NOTE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO GOODS_TBL (VERSION ,CODE ,NAME ,PRICE ,NOTE ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (1,'CODE3','UPDATE',1,'NOTE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO GOODS_TBL (VERSION ,CODE ,NAME ,PRICE ,NOTE ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (1,'CODE4','DELETE',1,'NOTE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);