CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE IF NOT EXISTS GOODS_TBL(
  ID BIGINT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  CODE VARCHAR(10) UNIQUE NOT NULL ,
  CATEGORY_ID BIGINT(10) UNSIGNED ,
  NAME VARCHAR(25) NOT NULL ,
  PRICE SMALLINT(4) UNSIGNED ,
  NOTE VARCHAR(64) NOT NULL
) DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS GOODS_STATUS_TBL(
  GOODS_ID BIGINT(10) UNSIGNED PRIMARY KEY NOT NULL ,
  VERSION INT(5) UNSIGNED NOT NULL DEFAULT '0' ,
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE ,
  CREATE_DATETIME DATETIME NOT NULL ,
  UPDATE_DATETIME DATETIME NOT NULL ,
  FOREIGN KEY(GOODS_ID) REFERENCES GOODS_TBL(ID)
) DEFAULT CHARSET=UTF8;

INSERT INTO GOODS_TBL (CODE ,CATEGORY_ID ,NAME ,PRICE ,NOTE)
  VALUES ('CODE1',1,'FIND',1,'NOTE');
INSERT INTO GOODS_STATUS_TBL (GOODS_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (1,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO GOODS_TBL (CODE ,CATEGORY_ID ,NAME ,PRICE ,NOTE)
  VALUES ('CODE2',1,'FIND',1,'NOTE');
INSERT INTO GOODS_STATUS_TBL (GOODS_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (2,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO GOODS_TBL (CODE ,CATEGORY_ID ,NAME ,PRICE ,NOTE)
  VALUES ('CODE3',1,'FIND',1,'NOTE');
INSERT INTO GOODS_STATUS_TBL (GOODS_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (3,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO GOODS_TBL (CODE ,CATEGORY_ID ,NAME ,PRICE ,NOTE)
  VALUES ('CODE4',1,'FIND',1,'NOTE');
INSERT INTO GOODS_STATUS_TBL (GOODS_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (4,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);