CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE IF NOT EXISTS CATEGORY_TBL(
  ID BIGINT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  CODE VARCHAR(10) UNIQUE NOT NULL ,
  NAME VARCHAR(25) NOT NULL ,
  NOTE VARCHAR(64) NOT NULL
) DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS CATEGORY_STATUS_TBL(
  CATEGORY_ID BIGINT(10) UNSIGNED UNIQUE NOT NULL ,
  VERSION INT(5) UNSIGNED NOT NULL DEFAULT '0' ,
  DELETE_FLAG BOOLEAN ,
  CREATE_DATETIME DATETIME NOT NULL ,
  UPDATE_DATETIME DATETIME NOT NULL ,
  FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY_TBL(ID)
) DEFAULT CHARSET=UTF8;

INSERT INTO CATEGORY_TBL (CODE ,NAME ,NOTE)
  VALUES ('CODEC1','GET','NOTE');
INSERT INTO CATEGORY_STATUS_TBL (CATEGORY_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (1,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO CATEGORY_TBL (CODE ,NAME ,NOTE)
  VALUES ('CODEC2','FIND','NOTE');
INSERT INTO CATEGORY_STATUS_TBL (CATEGORY_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (2,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO CATEGORY_TBL (CODE ,NAME ,NOTE)
  VALUES ('CODEC3','UPDATE','NOTE');
INSERT INTO CATEGORY_STATUS_TBL (CATEGORY_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (3,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO CATEGORY_TBL (CODE ,NAME ,NOTE)
  VALUES ('CODEC4','DELETE','NOTE');
INSERT INTO CATEGORY_STATUS_TBL (CATEGORY_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (4,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS GOODS_TBL(
  ID BIGINT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  CODE VARCHAR(10) UNIQUE NOT NULL ,
  CATEGORY_ID BIGINT(10) UNSIGNED ,
  NAME VARCHAR(25) NOT NULL ,
  PRICE SMALLINT(4) UNSIGNED ,
  NOTE VARCHAR(64) NOT NULL
) DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS GOODS_STATUS_TBL(
  GOODS_ID BIGINT(10) UNSIGNED PRIMARY KEY NOT NULL ,
  VERSION INT(5) UNSIGNED NOT NULL DEFAULT '0' ,
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE ,
  CREATE_DATETIME DATETIME NOT NULL ,
  UPDATE_DATETIME DATETIME NOT NULL ,
  FOREIGN KEY(GOODS_ID) REFERENCES GOODS_TBL(ID)
) DEFAULT CHARSET=UTF8;

INSERT INTO GOODS_TBL (CODE ,CATEGORY_ID ,NAME ,PRICE ,NOTE)
  VALUES ('CODEG1',1,'GET',1,'NOTE');
INSERT INTO GOODS_STATUS_TBL (GOODS_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (1,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO GOODS_TBL (CODE ,CATEGORY_ID ,NAME ,PRICE ,NOTE)
  VALUES ('CODEG2',2,'FIND',1,'NOTE');
INSERT INTO GOODS_STATUS_TBL (GOODS_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (2,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO GOODS_TBL (CODE ,CATEGORY_ID ,NAME ,PRICE ,NOTE)
  VALUES ('CODEG3',3,'UPDATE',1,'NOTE');
INSERT INTO GOODS_STATUS_TBL (GOODS_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (3,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO GOODS_TBL (CODE ,CATEGORY_ID ,NAME ,PRICE ,NOTE)
  VALUES ('CODEG4',4,'DELETE',1,'NOTE');
INSERT INTO GOODS_STATUS_TBL (GOODS_ID ,VERSION ,DELETE_FLAG ,CREATE_DATETIME ,UPDATE_DATETIME )
  VALUES (4,0,FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);