CREATE DATABASE IF NOT EXISTS ITEMS DEFAULT CHARACTER SET UTF8;
DROP TABLE IF EXISTS `ITEMS`.`GOODS_STATUS_TBL`;
DROP TABLE IF EXISTS `ITEMS`.`GOODS_TBL`;
DROP TABLE IF EXISTS `ITEMS`.`CATEGORY_STATUS_TBL`;
DROP TABLE IF EXISTS `ITEMS`.`CATEGORY_TBL`;


